FORMAT: 1A
HOST: http://localhost:9080/api

# Group Books API

Books API for example Books application.

## Books Collection [/books]

+ Attributes (Book Base)
    + isbn (string) - Book's ISBN

### List All Books [GET]
Retrieve a list of all books in the system
+ Response 200 (application/json)

        [
            {
                    "isbn": "111-1",
                    "title": "Java 8 Lamdas",
                    "author": "Richard Warburton",
                    "_links": {
                        "self": {
                            "href": "http://localhost:9080/api/book/111-1"
                        }
                    }
                },
                {
                    "isbn": "111-2",
                    "title": "An Introduction to Programming in Go",
                    "author": "Caleb Doxsey",
                    "_links": {
                        "self": {
                            "href": "http://localhost:9080/api/book/111-2"
                        }
                    }
                }
        ]

## Add a Book [/book]

+ Attributes (Book Base)
    + isbn (string) - Book's ISBN

### Add a New Book [POST]

Add a book

+ Request (application/json)

        {
            "isbn": "111-3",
            "title": "A test book title",
            "author": "Some author"
        }

+ Response 201 (application/json)

    + Body

            {
                "isbn": "111-3",
                "title": "A test book title",
                "author": "Some author",
                "_links": {
                    "self": {
                        "href": "http://localhost:9080/api/book/111-3"
                    }
                },
                "Books": {
                    "href": "http://localhost:9080/api/books"
                }
            }

## Book [/book/{isbn}]

+ Parameters
    + isbn (string) - ISBN of the Book
    
+ Attributes (Book Base)
    + isbn (string) - Book's ISBN
    
### Get a Book [GET]
Retrieve a Book using its ISBN

+ Response 200 (application/json)

    + Body
    
            {
                "isbn": "111-2",
                "title": "An Introduction to Programming in Go",
                "author": "Caleb Doxsey",
                "_links": {
                    "self": {
                        "href": "http://localhost:9080/api/book/111-2"
                    }
                }
            }
            
### Update a Book [PUT]
Update a Book's details

+ Request (application/json)

        { 
            "title": "A test book title (with a difference)",
            "author": "Some author"
        }
        
+ Response 200 (application/json)

        {
            "isbn": "111-3",
            "title": "A test book title (with a difference)",
            "author": "Some author",
            "_links": {
                "self": {
                    "href": "http://localhost:9080/api/book/111-3"
                }
            },
            "Books": {
                "href": "http://localhost:9080/api/books"
            }
        }
        
# Data Structures

## Book Base (object)
+ title (string) - Book title
+ author (string) - Book author
